version: "3.8"
volumes:
  cs301_mongodb:
services:
  mongodb:
    image: mongo:latest
    container_name: "cs301_mongodb"
    ports:
      - "27017:27017"
    volumes:
      - cs301_mongodb:/data/db
  cs301-api:
    container_name: cs301-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "11112:11112"
    volumes:
      - ./:/app
      - ~/.aws/credentials:/root/.aws/credentials
